# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - oraclejdk12

services:
 - postgresql
before_install:
 - psql -c 'create database parser;' -U postgres

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту youremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -14GameOver@mail.ru
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="dfed6202-d2dd-4af6-89f0-f5b96b890634"